### ISSUE TITLE
Add CC-BY Author

### ISSUE THREAD

**Issue by DeastinY** [GOCc3/gocc3-website#5]
For gocc3-website/images/me.jpg you need to make the original author visible.
Check out this : https://wiki.creativecommons.org/wiki/Best_practices_for_attribution

**Comment by thies23** [comment]
Its not under cc-by released & changed.
But will do so.

**Comment by DeastinY** [comment]
https://en.wikipedia.org/wiki/Gummy_bear#/media/File:Gummy_bears.jpg
states it's CC-BY-SA oO

**Comment by thies23** [comment]
Added a Link to original image.
